server:
  port: ${PORT:8080}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  aws:
    region: ${AWS_REGION:us-east-2}
  dynamodb:
    table: ${DYNAMODB_TABLE:transactions}
    endpoint: ${DYNAMODB_ENDPOINT:}
  kafka:
    enabled: ${APP_KAFKA_ENABLED:false}
